# Generated by Django 3.2.15 on 2022-09-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='zendesk_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
