# Generated by Django 3.2.15 on 2022-09-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account_zendesk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='zendesk_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
