# Generated by Django 3.2.15 on 2023-07-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_account_zendesk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'User')], null=True),
        ),
    ]
