# Generated by Django 3.2.15 on 2023-07-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Admin', 'Admin'), ('User', 'User')], null=True),
        ),
    ]
