# Generated by Django 3.2.15 on 2022-09-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('Ticket_ID', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Priority', models.CharField(blank=True, choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=100, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
