# Generated by Django 3.2.15 on 2022-09-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='mobile',
            new_name='Phone_Number',
        ),
    ]
