# Generated by Django 3.2.15 on 2022-09-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_rename_mobile_ticket_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
